### ISSUE TITLE
Unable to execute payout due to go-tezos bug

### ISSUE THREAD

**Issue by leopoldjoy** [DefinitelyNotAGoat/payman#8] opened 2019-05-27 00:58 UTC
I am trying to execute the `payout` subcommand by running:

```
./payman payout --delegate=tz3NdTPb3Ax2rVW2Kq9QEdzfYFkRwhrQRPhX --cycle=190 --node=https://alphanet.tezrpc.me --fee=0.1 --payout-min=10000 --secret=<edesk...> --password=<password> --network-fee=1420
```

However, I'm getting this error:

```
payout.go:133: could not create batch payment: failed to Pre-Apply: could not preapply operation: bad response code 500
```

I am able to generate a report with the `report` subcommand without issue. However, I am getting this error when running the `payout` subcommand on both `Alphanet` and `Mainnet`.

I've tracked down the error to [this line](https://github.com/DefinitelyNotAGoat/go-tezos/blob/ffffd04391e8528c3f678d0aa8d27e277728fb7e/operations.go#L97) in [`go-tezos`](https://github.com/DefinitelyNotAGoat/go-tezos). It seems that validation fails when comparing the batch payment generated by `go-tezos` against the node. It appears to also relate to [this](https://github.com/DefinitelyNotAGoat/go-tezos/issues/74) `go-tezos` issue.

**Comment by zhanglianghui** [comment] 2019-05-28 10:15
Is the author missing? Is no one solving the problem?

**Comment by leopoldjoy** [comment] 2019-05-28 11:09
@zhanglianghui I believe @DefinitelyNotAGoat is active on the repo, he just added [this feature](https://github.com/DefinitelyNotAGoat/payman/issues/7) last week. If I can find some time, I'll dig into this problem further.

**Comment by zhanglianghui** [comment] 2019-05-28 13:37
> @zhanglianghui I believe @DefinitelyNotAGoat is active on the repo, he just added [this feature](https://github.com/DefinitelyNotAGoat/payman/issues/7) last week. If I can find some time, I'll dig into this problem further.

Ok, thanks. However, this problem is a little tricky. I don't know why the transaction signed by go-tezos will fail after sent to node, and no logs can be found from node.

**Comment by DefinitelyNotAGoat** [comment] 2019-05-31 01:05
Thanks for reporting. Yeah I believe @zhanglianghui has reported this issue in Go Tezos. I will try to find some time tomorrow evening to debug what's going on. I apologize for the delay, I'm currently working a part time job in my evenings that's taking a lot of my time.

**Comment by DefinitelyNotAGoat** [comment] 2019-05-31 01:16
I tried to reproduce this issue locally and I'm having a really hard time: 
```
./payman payout --delegate=tz3NdTPb3Ax2rVW2Kq9QEdzfYFkRwhrQRPhX --cycle=190 --node=https://alphanet.tezrpc.me --fee=0.1 --payout-min=10000 --secret=edesk1Qx5JbctVnFVHL4A7BXgyExihHfcAHRYXoxkbSBmKqP2Sp92Gg1xcU8mqqu4Qi9TXkXwomMxAfy19sWAgCm --password=abcd1234 --network-fee=1420
2019/05/30 21:12:09 reporting.go:24: Successful operation: "onoxscii3YFU4APADTTcu2Tr4NHhorqdbsyJMRBRsjeVFoTsMDQ"

+--------------------------------------+----------+-----------+----------+-----------+
|               ADDRESS                |  SHARE   |   GROSS   |   FEE    |    NET    |
+--------------------------------------+----------+-----------+----------+-----------+
| KT1Wgq75N1BcwxXVzsLXQDbGmjKhUceK7JvY | 0.004290 |  0.607754 | 0.060775 |  0.546979 |
| KT1MSqpPNTokMdjuZiNySHc4s5KNvZ9LAaj9 | 0.020130 |  2.851542 | 0.285154 |  2.566388 |
| KT1Ug1xAafJyhyFoPoGNTZi2nVxTeeD9fU2Z | 0.121720 | 17.242672 | 1.724267 | 15.518405 |
| KT1RLABRR7xHWhXq246DMaHqWaZTJ4okEdRE | 0.001016 |  0.143862 | 0.014386 |  0.129476 |
| KT1CFABfscnR48qm682WoPYha2HyAGcQinv8 | 0.001118 |  0.158411 | 0.015841 |  0.142570 |
+--------------------------------------+----------+-----------+----------+-----------+
|                                         TOTAL   | 21.004241 | 2.100423 | 18.903818 |
+--------------------------------------+----------+-----------+----------+-----------+```

If I can't reproduce I'll just audit the code tomorrow. Can you please share any additional details that you can think of?

**Comment by zhanglianghui** [comment] 2019-05-31 01:50
> I tried to reproduce this issue locally and I'm having a really hard time:
> 
> ```
> ./payman payout --delegate=tz3NdTPb3Ax2rVW2Kq9QEdzfYFkRwhrQRPhX --cycle=190 --node=https://alphanet.tezrpc.me --fee=0.1 --payout-min=10000 --secret=edesk1Qx5JbctVnFVHL4A7BXgyExihHfcAHRYXoxkbSBmKqP2Sp92Gg1xcU8mqqu4Qi9TXkXwomMxAfy19sWAgCm --password=abcd1234 --network-fee=1420
> 2019/05/30 21:12:09 reporting.go:24: Successful operation: "onoxscii3YFU4APADTTcu2Tr4NHhorqdbsyJMRBRsjeVFoTsMDQ"
> 
> +--------------------------------------+----------+-----------+----------+-----------+
> |               ADDRESS                |  SHARE   |   GROSS   |   FEE    |    NET    |
> +--------------------------------------+----------+-----------+----------+-----------+
> | KT1Wgq75N1BcwxXVzsLXQDbGmjKhUceK7JvY | 0.004290 |  0.607754 | 0.060775 |  0.546979 |
> | KT1MSqpPNTokMdjuZiNySHc4s5KNvZ9LAaj9 | 0.020130 |  2.851542 | 0.285154 |  2.566388 |
> | KT1Ug1xAafJyhyFoPoGNTZi2nVxTeeD9fU2Z | 0.121720 | 17.242672 | 1.724267 | 15.518405 |
> | KT1RLABRR7xHWhXq246DMaHqWaZTJ4okEdRE | 0.001016 |  0.143862 | 0.014386 |  0.129476 |
> | KT1CFABfscnR48qm682WoPYha2HyAGcQinv8 | 0.001118 |  0.158411 | 0.015841 |  0.142570 |
> +--------------------------------------+----------+-----------+----------+-----------+
> |                                         TOTAL   | 21.004241 | 2.100423 | 18.903818 |
> +--------------------------------------+----------+-----------+----------+-----------+
> ```
> 
> If I can't reproduce I'll just audit the code tomorrow. Can you please share any additional details that you can think of?

The alphanet is OK, you should try on the **mainnet**.
When call preApplyOperations on mainnet, the request will return error: bad response code 500.

**Comment by DefinitelyNotAGoat** [comment] 2019-05-31 02:17
@zhanglianghui If your using a the public mainnet nodes, it's because they block those RPC's. But because @leopoldjoy reproduced it on alphanet I don't think that's the issue. I'm unable to reproduce it, but I'm currently adding much better error checking to Go Tezos so that if you reproduce it, we should know exactly where it's at.

**Comment by zhanglianghui** [comment] 2019-05-31 02:27
> @zhanglianghui If your using a the public mainnet nodes, it's because they block those RPC's. But because @leopoldjoy reproduced it on alphanet I don't think that's the issue. I'm unable to reproduce it, but I'm currently adding much better error checking to Go Tezos so that if you reproduce it, we should know exactly where it's at.

How can the mainnet node block those RPC's?  I can not find any config to control node's RPC.

**Comment by DefinitelyNotAGoat** [comment] 2019-05-31 02:29
@zhanglianghui I'm talking about public nodes that you don't control. The public nodes listed on tzscan.io have proxies in front of them that block certain requests. If your using your own personal mainnet node, then the correct RPC's should be exposed.

**Comment by zhanglianghui** [comment] 2019-05-31 02:34
> @zhanglianghui I'm talking about public nodes that you don't control. The public nodes listed on tzscan.io have proxies in front of them that block certain requests. If your using your own personal mainnet node, then the correct RPC's should be exposed.

Yes, I am using my personal mainnet node, and how can I make sure the RPC's is exposed?

**Comment by DefinitelyNotAGoat** [comment] 2019-05-31 03:14
You don't have to do anything, all the RPC's you need are exposed.

**Comment by DefinitelyNotAGoat** [comment] 2019-05-31 22:47
@zhanglianghui, and @leopoldjoy would you both mind updating to v1.0.5, I bubbled up errors better so you should see the actual response you get not just the status code.

**Comment by zhanglianghui** [comment] 2019-06-02 01:00
> @zhanglianghui, and @leopoldjoy would you both mind updating to v1.0.5, I bubbled up errors better so you should see the actual response you get not just the status code.

I have try with newest release v1.0.5, and got error detail, that may be helpful for you to debug.

>  could not create batch payment: could not preapply operations '/chains/main/blocks/head/helpers/preapply/operations' with contents '[{\"contents\":[{\"kind\":\"transaction\",\"source\":\"tz1SmnG8bx2obaT9gv6tXajo4ohzpoMBVhfQ\",\"fee\":\"1500\",\"counter\":\"1393247\",\"gas_limit\":\"10200\",\"storage_limit\":\"0\",\"amount\":\"81900\",\"destination\":\"KT1HQejJGrsb6qq4vLncj1TbQWtJZ2ahVQ3z\"}],\"branch\":\"BMR5A4CQqtK7mWXGuQKovRrLg6VKMAcBHiafeyrSAzxXwb3aLqq\",\"protocol\":\"Pt24m4xiPbLDhVgVfABUjirbmda3yohdN82Sp9FeuAXJ4eV9otd\",\"signature\":\"edsigu4HpNfjWxYYeVUy5HCqAMn6czWrkDHiHQykf3acPMuhgNaPcDFf4nnWVZejNuGPtzDU5vZYpRSbwknDkk7P1zdTExEvL9Q\"}]': 500 error: [{\"kind\":\"branch\",\"id\":\"proto.004-Pt24m4xi.contract.unrevealed_key\",\"contract\":\"tz1SmnG8bx2obaT9gv6tXajo4ohzpoMBVhfQ\"}]

**Comment by DefinitelyNotAGoat** [comment] 2019-06-02 18:51
Thanks @zhanglianghui so that's probably your issue. The wallet you are using is not revealed to the network yet. You need to run `./tezos-client reveal key for tz1SmnG8bx2obaT9gv6tXajo4ohzpoMBVhfQ`. 

@leopoldjoy Can you confirm you get the same error?

**Comment by leopoldjoy** [comment] 2019-06-02 22:04
@DefinitelyNotAGoat I already revealed my wallet to the network. I am receiving a different error. When I run:

```
./payman payout --delegate=tz3NdTPb3Ax2rVW2Kq9QEdzfYFkRwhrQRPhX --cycle=190 --node=tezos-dev.cryptonomic-infra.tech --fee=0.1 --payout-min=10000 --secret=edesk1Qx5JbctVnFVHL4A7BXgyExihHfcAHRYXoxkbSBmKqP2Sp92Gg1xcU8mqqu4Qi9TXkXwomMxAfy19sWAgCm --password=abcd1234 --network-fee=1420
```

I get this error:

```
2019/06/03 00:00:30 payout.go:133: could not create batch payment: could not forge operation '/chains/main/blocks/head/helpers/forge/operations' with contents '{"contents":
[{"kind":"transaction","source":"tz1SmnG8bx2obaT9gv6tXajo4ohzpoMBVhfQ","fee":"1420","counter":"62304","gas_limit":"10200","storage_limit":"0","amount":"129476","destination":"KT1RLABRR7xHWhXq246DMaHqWaZTJ4okEdRE"},
{"kind":"transaction","source":"tz1SmnG8bx2obaT9gv6tXajo4ohzpoMBVhfQ","fee":"1420","counter":"62305","gas_limit":"10200","storage_limit":"0","amount":"2566388","destination":"KT1MSqpPNTokMdjuZiNySHc4s5KNvZ9LAaj9"},
{"kind":"transaction","source":"tz1SmnG8bx2obaT9gv6tXajo4ohzpoMBVhfQ","fee":"1420","counter":"62306","gas_limit":"10200","storage_limit":"0","amount":"15518405","destination":"KT1Ug1xAafJyhyFoPoGNTZi2nVxTeeD9fU2Z"},
{"kind":"transaction","source":"tz1SmnG8bx2obaT9gv6tXajo4ohzpoMBVhfQ","fee":"1420","counter":"62307","gas_limit":"10200","storage_limit":"0","amount":"142570","destination":"KT1CFABfscnR48qm682WoPYha2HyAGcQinv8"},
{"kind":"transaction","source":"tz1SmnG8bx2obaT9gv6tXajo4ohzpoMBVhfQ","fee":"1420","counter":"62308","gas_limit":"10200","storage_limit":"0","amount":"546979","destination":"KT1Wgq75N1BcwxXVzsLXQDbGmjKhUceK7JvY"}
],"branch":"BDLSqXcuBq4fkeS85oW6UsUNbCx2SRvPTjSGgnbRcmAzn2982X9"}': 405 error: 
```

It seems that, as discussed earlier in the threat, the patch payment creation if failing.

**Comment by zhanglianghui** [comment] 2019-06-03 03:01
> Thanks @zhanglianghui so that's probably your issue, and also explains why I can't reproduce it. The wallet you are using is not revealed to the network yet. You need to run `./tezos-client reveal key for tz1SmnG8bx2obaT9gv6tXajo4ohzpoMBVhfQ`.
> 
> @leopoldjoy Can you confirm you get the same error?

Wow, thank you very much. I misunderstand the error msg.

**Comment by leopoldjoy** [comment] 2019-06-04 14:15
@DefinitelyNotAGoat Any idea what might be causing the above error? Also (related), any idea of a rough ETA for a fix for this problem? I'll try to find some time to jump into it also.

**Comment by DefinitelyNotAGoat** [comment] 2019-06-04 14:36
@leopoldjoy I'll have time to look into it more this weekend, but with the error code being 405 method not allowed, I suspect that `tezos-dev.cryptonomic-infra.tech` is blocking the RPC. Have you tried it with a local node in archive mode?

**Comment by leopoldjoy** [comment] 2019-06-05 00:56
@DefinitelyNotAGoat I discovered a bug in [`go-tezos`](https://github.com/DefinitelyNotAGoat/go-tezos) that was causing the problem. I've opened a PR with a super simple fix here: https://github.com/DefinitelyNotAGoat/go-tezos/pull/75. Essentially RPC node endpoints using HTTPS were not being handled properly—`http://` was being prepended to the node endpoint (e.g. resulting in: `http://https//alphanet.tezrpc.me`).

**Comment by DefinitelyNotAGoat** [comment] 2019-06-05 03:20
Awesome man! Thank you! I got it merged. I'll close this ticket in 48 hours, if no issues are reported.

**Comment by bneiluj** [comment] 2019-06-05 08:38
Awesome 😀

**Closed** 2019-06-05 21:44 UTC
Labels: bug

**Comment by leopoldjoy** [comment] 2019-06-05 22:11
Perfect, working properly on alphanet for me now 👍
